blueprint:
  name: Aqara switch binary_sensor
  description: Bind action to Aqara switch
  domain: automation
  input:
    switch_id:
      name: Binary sensor entity
      description: The binary_sensor used to trigger the automation
      selector:
        entity:
          domain: binary_sensor
    single_click_action:
      name: Single click action
      description: The action(s) to launch for a single short click
      default: []
      selector:
        action: {}
    double_click_action:
      name: Double click action
      description: The action(s) to launch for a double click
      default: []
      selector:
        action: {}
    long_click_action:
      name: Long click action
      description: The action(s) to launch for a long click
      default: []
      selector:
        action: {}
mode: single
max_exceeded: silent
trigger:
  - platform: event
    event_type: xiaomi_aqara.click
    event_data:
      entity_id: !input 'switch_id'
action:
  - variables:
    click_type: '{{ trigger.event.data.click_type }}'
  - choose:
    - conditions: '{{ click_type == ''hold'' }}'
      sequence: !input 'long_click_action'
    - conditions: '{{ click_type == ''single'' }}'
      sequence: !input 'single_click_action'
    - conditions: '{{ click_type == ''double'' }}'
      sequence: !input 'double_click_action'
